### ISSUE TITLE
Code review of kanban 

### ISSUE THREAD

**Issue by amiraabouhadid** [amiraabouhadid/GottaCatchEmAll#21]
## Description

In this project, we distributed tasks among team members using GitHub issues and basic Kanban board.
The GitHub project url:  https://github.com/amiraabouhadid/GottaCatchEmAll/projects/1
There are 2 members in this team working on the JS capstone project: 

- Amira Abouhadid
- Ammar Hamlaoui

### General requirements

- [x] The template provided is used. 
- [x] The documentation is professional.

### Project requirements

- Join a Zoom call with your team. Only one person needs to copy the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects).
- Open the GitHub project (Kanban board) in your team repo.
- Make sure that in the card titles you can see: Student A, Student B, or Student C.
- Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
- If your group includes two people - remove all cards with Student C in the title.
- Decide who in your team is Student A, Student B, or Student C.
- Each of the team members should assign themselves to the correct cards. Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
- [Open a new issue in your repository](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue).
  - In its description, paste a link to your GitHub project.
  - Add a note telling the reviewer how many people there are in your team.
- Use the issue link to ask for a review. A Code Reviewer will leave you feedback in the issue's comment.
  - As it is your first time using a GitHub project and Kanban board, we need to double-check your setup to avoid problems while working on your project.

Thank you for taking the time to review this pull request.

**Comment by ReshyResh** [comment]
# Hi team, 

### Well done setting up the Kanban board, you may start your project!

#### Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_
