### ISSUE TITLE
Suggestions to improve 

### ISSUE THREAD

**Issue by souad988** [amiraabouhadid/GottaCatchEmAll#24]
First, We want to express our appreciation for the work you did , and here are some suggestions that could make this project more solid and complete:

-i think  it would be better if you reduce the cards size so you can display  more than 3 cards on a port view.
-since you have multiple imgs for each pokemon you can use a kind of carousel inside the cards to display the imgs 

Please feel free to ask for any more clarification about the issues we raised.
Cheers 🚀

**Comment by damdafayton** [comment]
- Everything looks well organized
- Below modules seem to have similar code. They might be merged into one single function and modified with a function argument.

https://github.com/amiraabouhadid/GottaCatchEmAll/blob/development/src/modules/Ability.js
https://github.com/amiraabouhadid/GottaCatchEmAll/blob/development/src/modules/Type.js

**Comment by amiraabouhadid** [comment]
Hey @souad988 @damdafayton,

Thanks for the suggestions! We have implemented them. Please check the development branch for the newest version of the app. 
Many thanks,
Amira
